### PR TITLE
Fix check_process

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by mh4ckt3mh4ckt1c4s** [comment]
!testme

**Comment by mh4ckt3mh4ckt1c4s** [comment]
I thought I was added to the YunoHost-Apps org but I was just added to this repo so I'm not able to launch CI tests from comments 🙂. A few remarks : 
- All the linter warnings are fixed on the master branch. Dunno why there are warnings here. You should rebase from the master branch (which is the most up-to-date, as I was working alone and the app was not working I was committing on master directly).
- Also on the master branch, the multi-instance test was disabled (as it is not supposed to be a multi-instance app), the `upgrade from=CommitHash` test was commented out and most of the tests were passing.

**Comment by ericgaspar** [comment]
!tetstme

**Comment by mh4ckt3mh4ckt1c4s** [comment]
!testme

**Comment by mh4ckt3mh4ckt1c4s** [comment]
I don't know why the backup / restore tests keeps failing. It's working fine when I experiment with my Virtualbox test instance. I'm still investigating.

**Comment by Typhlos** [comment]
I might have found why: when you restore the app, you do not seem to recreate the systemd service associated as you do in the install/upgrade script with `ynh_add_uwsgi_service`. If you go see the full CI logs, you'll see in the backup/restore test that the service `uwsgi-app@searxng.service` is not listed when the CI job does a `systemctl list-units`.

**Comment by mh4ckt3mh4ckt1c4s** [comment]
I think you're right, I'm gonna fix this but in another PR to keep things clean. I'm merging this with the updated `check_process` config.

**Pull request merged**
